### ISSUE TITLE
INVALID_SOCKET value is incorrect

### ISSUE THREAD

**Issue by disarray2077** [jayrulez/Win32-Beef#3]
INVALID_SOCKET should be equal to ~0 (or `SOCKET.MaxValue`) but currently it's the value of `uint32.MaxValue`.

https://github.com/jayrulez/Win32-Beef/blob/d1390de8928a3e519f2f99a14be17a977a11170f/Win32/src/Generated/Networking/WinSock.bf#L932

**Comment by jayrulez** [comment]
Leaving this here: https://github.com/microsoft/win32metadata/issues/848

It seems the JSON data was generated before the fix for this was made.

The json data is generated from version v15.x while the fix was made in v22.0.14-preview.

I've tried regenerating the json from @marlersoft 's repo but some assumptions about the metadata seems to be broken. 

I'm considering generating the bindings from the metadata directly to avoid situations like this... This would take some time though so for now, I will patch the generator to handle this while I work out a better solution.
